# Generated by Django 4.2.7 on 2023-12-15 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=300, null=True)),
                ('ippis_no', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='IPPIS Number')),
                ('file_no', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='File Number')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Phone Number')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
