# Generated by Django 4.2.7 on 2023-12-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proslip', '0002_rename_phone_profile_phone_no_profile_dept_or_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('year', models.DateField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proslip.profile')),
            ],
        ),
    ]
