# Generated by Django 4.2.7 on 2023-12-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proslip', '0003_payslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='year',
        ),
        migrations.AlterField(
            model_name='payslip',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proslip.profile'),
        ),
    ]
