# Generated by Django 4.2.7 on 2023-12-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proslip', '0004_remove_payslip_month_remove_payslip_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
