# Generated by Django 4.2.7 on 2023-12-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proslip', '0006_rename_file_payslip_slip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='slip',
            new_name='file',
        ),
    ]
